version: '3.2'

services:
  db:
      image: mysql:5.7
      container_name: mysql
      restart: always
      ports:
        - '6033:3306'
      environment:
        MYSQL_ROOT_PASSWORD: password
  
  pma:
      depends_on:
      - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
      - '8080:80'
      environment:
        PMA_HOST: db